### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gbbk7ble/BeautifulSoup/ - When trying to install

### ISSUE THREAD

**Issue by grishakumar** [SimplySecurity/SimplyEmail#47]
==========================================================================
 SimpleEmail Setup Script | [Updated]: 2016
==========================================================================
 [Web]: Http://CyberSyndicates.com | [Twitter]: @KillSwitch-GUI
==========================================================================
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.16.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-lxml is already the newest version (4.2.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
antiword is already the newest version (0.37-11+b1).
grep is already the newest version (3.1-2).
libxml2-dev is already the newest version (2.9.4+dfsg1-6.1).
libxslt1-dev is already the newest version (1.1.29-5).
odt2txt is already the newest version (0.5-1+b2).
python-dev is already the newest version (2.7.14-4).
wget is already the newest version (1.19.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-virtualenv is already the newest version (15.1.0+ds-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.16.3-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-lxml is already the newest version (4.2.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
antiword is already the newest version (0.37-11+b1).
grep is already the newest version (3.1-2).
libxml2-dev is already the newest version (2.9.4+dfsg1-6.1).
libxslt1-dev is already the newest version (1.1.29-5).
odt2txt is already the newest version (0.5-1+b2).
python-dev is already the newest version (2.7.14-4).
wget is already the newest version (1.19.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-virtualenv is already the newest version (15.1.0+ds-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: autoenv in /usr/local/lib/python2.7/dist-packages
Using base prefix '/usr'
New python executable in /root/scripts/SimplyEmail/SE/bin/python3
Not overwriting existing python script /root/scripts/SimplyEmail/SE/bin/python (you must use /root/scripts/SimplyEmail/SE/bin/python3)
Installing setuptools, pip, wheel...done.
Collecting BeautifulSoup==3.2.1 (from -r setup/requirments.txt (line 1))
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gbbk7ble/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gbbk7ble/BeautifulSoup/

**Comment by sumgr0** [comment]
Getting the same error while installing simply email. Any chance this can be fixed?

**Comment by genert** [comment]
What OS are you using? 

However, you can install the dependencies manually, and it will work regardless.

`pip install -r setup/requirments.txt`

**Comment by FoxSca** [comment]
pip install -r setup/requirments.txt
Collecting BeautifulSoup==3.2.1 (from -r setup/requirments.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p_ghqs78/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-p_ghqs78/BeautifulSoup/

Linux  4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

**Comment by Hak4Kidz** [comment]
Having the same issue as BlAd373.

OSX 10.13.6
MacBook Pro (15-inch, 2017)

pip install -r setup/requirments.txt 
Collecting BeautifulSoup==3.2.1
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/wv/gkpqflw15cdgytzwcv90jtp00000gn/T/pip-install-ztw170cy/BeautifulSoup/setup.py'"'"'; __file__='"'"'/private/var/folders/wv/gkpqflw15cdgytzwcv90jtp00000gn/T/pip-install-ztw170cy/BeautifulSoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/wv/gkpqflw15cdgytzwcv90jtp00000gn/T/pip-install-ztw170cy/BeautifulSoup/pip-egg-info
         cwd: /private/var/folders/wv/gkpqflw15cdgytzwcv90jtp00000gn/T/pip-install-ztw170cy/BeautifulSoup/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wv/gkpqflw15cdgytzwcv90jtp00000gn/T/pip-install-ztw170cy/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

TIA,
Heal

**Comment by Sauruswarrior** [comment]
Having the Same Issue looks like its an issue since old Beautiful Soup is no longer working and this doesn't use Beautiful Soup 4 package

**Comment by Kdashtobi** [comment]
I have the same issue :( 

pip install -r setup/requirments.txt 
Collecting BeautifulSoup==3.2.1
  Using cached BeautifulSoup-3.2.1.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eg43p2t0/BeautifulSoup/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eg43p2t0/BeautifulSoup/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-v6pi5bca
         cwd: /tmp/pip-install-eg43p2t0/BeautifulSoup/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-eg43p2t0/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
