### ISSUE TITLE
ImportError: No module named fake_useragent

### ISSUE THREAD

**Issue by brokenhungry** [SimplySecurity/SimplyEmail#69]
## SimplyEmail Version
1.4.5

## OS Information (Linux flavor, Python version)
4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-2kali1 (2019-05-15) x86_64

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
after running ./setup.sh I cd .. back to SimplyEmail/
i then ran ./SimplyEmail.py and got nadda but:
--------
Traceback (most recent call last):
  File "./SimplyEmail.py", line 13, in <module>
    from Helpers import helpers
  File "/home/oaken/GIT/SimplyEmail/Helpers/helpers.py", line 12, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
------------------------

## Any additional information

**Comment by vizzdoom** [comment]
I fixed it by using pip install -r setup/requirements.txt on Kali
