### ISSUE TITLE
I would like to run SimplyEmail in cronjob.

### ISSUE THREAD

**Issue by Winnies31** [SimplySecurity/SimplyEmail#74]
## SimplyEmail Version
**last**

## OS Information (Linux flavor, Python version)
**kali linux
python2.7**

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
**I can't get the script to work in cronjob**

## Screenshot of error, embedded text output, or Pastebin link to the error 

 This is the error when I run script in ROOT :

Traceback (most recent call last):
  File "/root/SimplyEmail/SimplyEmail.py", line 113, in <module>
    main()
  File "/root/SimplyEmail/SimplyEmail.py", line 108, in main
    TaskStarter(version)
UnboundLocalError: local variable 'version' referenced before assignment

This my command line :
/usr/bin/python2.7 /root/SimplyEmail/SimplyEmail.py -h

Thank's for your help.

**Comment by Winnies31** [comment]
I, when I execute cron, I have this error :

'GlobalSettings'
'GlobalSettings'
 ============================================================
 Current Version: (inhibé) Website: CyberSyndicates.com
 ============================================================
 Twitter: @real_slacker007 |  Twitter: @Killswitch_gui
 ============================================================
------------------------------------------------------------
   ______  ________                       __ __
 /      \/        |                     /  /  |
/$$$$$$  $$$$$$$$/ _____  ____   ______ $$/$$ |
$$ \__$$/$$ |__   /     \/    \ /      \/  $$ |
$$      \$$    |  $$$$$$ $$$$  |$$$$$$  $$ $$ |
 $$$$$$  $$$$$/   $$ | $$ | $$ |/    $$ $$ $$ |
/  \__$$ $$ |_____$$ | $$ | $$ /$$$$$$$ $$ $$ |
$$    $$/$$       $$ | $$ | $$ $$    $$ $$ $$ |
 $$$$$$/ $$$$$$$$/$$/  $$/  $$/ $$$$$$$/$$/$$/

------------------------------------------------------------
'GlobalSettings'
'GlobalSettings'
Traceback (most recent call last):
  File "/root/SimplyEmail/SimplyEmail.py", line 114, in <module>
    main()
  File "/root/SimplyEmail/SimplyEmail.py", line 109, in main
    TaskStarter(version)
  File "/root/SimplyEmail/SimplyEmail.py", line 86, in TaskStarter
    V.VersionRequest()
  File "/root/SimplyEmail/Helpers/VersionCheck.py", line 25, in VersionRequest
    if self.Start == "Yes":
AttributeError: 'VersionCheck' object has no attribute 'Start'


Thank's for your help.
